name: fne_app
description: "FNE Express - Générateur de Factures Normalisées Électroniques"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dio: ^5.9.2
  toastification: ^3.0.3
  file_picker: ^10.3.10
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter

  # Added dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  share_plus: 7.2.2
  intl: 0.20.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  googleai_dart: ^3.6.0
  flutter_dotenv: ^6.0.0
  pdfx: ^2.8.0
  webview_flutter: ^4.13.1
  flutter_sharing_intent: ^1.1.1
  flutter_native_splash: ^2.4.7
  url_launcher: ^6.3.1
  pdf: ^3.11.0
  printing: ^5.13.0
  to_csv: ^6.0.1
  syncfusion_flutter_xlsio: ^28.1.33
  supabase_flutter: ^2.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android >= 5.0

flutter_native_splash:
  color: "#f5f5ed"
  icon_background_color: "#f5f5ed"
  image: "assets/images/logo.png"
  android_12:
    color: "#f5f5ed"
    icon_background_color: "#f5f5ed"
    image: "assets/images/logo.png"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png
